"use client";
import ContactForm from '@/components/ContactForm';
import TextOverColor from '@/components/TextOverColor';
import Image from 'next/image';
import Link from 'next/link';
import React, { useState } from 'react'
import { BsArrowRight, BsSearch } from 'react-icons/bs';
import { FiArrowRight } from 'react-icons/fi';

const insights = [
    {
        title: "Article",
        description:
            "Leidos reports strong Q2, raises full-year guidance",
        image: "/images/insights/insight1.jpg",
        buttonText: "Read More",
        buttonLink: "/insights",
    },
    {
        title: "News",
        description:
            "Leidos posts strong second quarter fiscal year 2025 results",
        image: "/images/insights/insight1.jpg",
        buttonText: "Read More",
        buttonLink: "/insights",
    },
    {
        title: "News",
        description:
            "Leidos Australia to provide managed ICT services to Geoscience Australia",
        image: "/images/insights/insight1.jpg",
        buttonText: "Read More",
        buttonLink: "/insights",
    },
    {
        title: "White Paper",
        description:
            "Maximising the benefit of Information Sharing across AUKUS",
        image: "/images/insights/insight1.jpg",
        buttonText: "Read More",
        buttonLink: "/insights",
    },
];

const filters = [
    {
        name: "Health & Civil",
        heading: "Health & Civil Solutions",
        paragraph:
            "We provide innovative healthcare and civil solutions, enhancing public well-being through technology and expert support.",
        gradient: "from-[#3b414d] to-[#335f80]",
    },
    {
        name: "National Security",
        heading: "National Security Solutions",
        paragraph:
            "Empowering national defense with cutting-edge intelligence, surveillance, and reconnaissance systems.",
        gradient: "from-[#335f80] to-[#6c87a5]",
    },
    {
        name: "Commercial & International",
        heading: "Commercial & International Programs",
        paragraph:
            "Delivering commercial space, telecom, and defense innovations globally with high-impact collaborations.",
        gradient: "from-[#6c87a5] to-emerald-500",
    },
    {
        name: "Digital Modernization",
        heading: "Digital Modernization",
        paragraph:
            "Transforming legacy systems into smart digital ecosystems with AI, cloud, and cybersecurity.",
        gradient: "from-emerald-500 to-sky-600",
    },
    {
        name: "Defense Systems",
        heading: "Defense Systems",
        paragraph:
            "The Defense Systems Sector develops and produces advanced space, aerial, surface, and sub-surface manned and un-manned defense systems.",
        gradient: "from-sky-600 to-violet-800",
    },
];


const contents = [
    {
        name: "About Leidos",
        paragraph:
            "Leidos is an industry and technology leader serving government and commercial customers with smarter, more efficient digital and mission innovations. Headquartered in Reston, Virginia, with 47,000 global employees, Leidos reported annual revenues of approximately $16.7 billion for the fiscal year ended January 3, 2025.  For more information, visit www.Leidos.com.",
    },
    {
        name: "Pay & Benefits",
        paragraph:
            "Pay and benefits are fundamental to any career decision. That's why we craft compensation packages that reflect the importance of the work we do for our customers. Employment benefits include competitive compensation, Health and Wellness programs, Income Protection, Paid Leave and Retirement. More details are available here.",
    },
    {
        name: "Secure Your Data",
        paragraph:
            "Beware of fake employment opportunities using Leidos&apos; name. Leidos will never ask you to provide payment-related information during any part of the employment application process (i.e., ask you for money), nor will Leidos ever advance money as part of the hiring process (i.e., send you a check or money order before doing any work). Further, Leidos will only communicate with you through emails that are generated by the Leidos.com automated system never from free commercial services (e.g., Gmail, Yahoo, Hotmail) or via WhatsApp, Telegram, etc. If you received an email purporting to be from Leidos that asks for payment-related information or any other personal information (e.g., about you or your previous employer), and you are concerned about its legitimacy, please make us aware immediately by emailing us at LeidosCareersFraud@leidos.com.",
    },
     {
        name: "Commitment to Non-Discrimination",
        paragraph:
            "All qualified applicants will receive consideration for employment without regard to sex, race, ethnicity, age, national origin, citizenship, religion, physical or mental disability, medical condition, genetic information, pregnancy, family structure, marital status, ancestry, domestic partner status, sexual orientation, gender identity or expression, veteran or military status, or any other basis prohibited by law. Leidos will also consider for employment qualified applicants with criminal histories consistent with relevant laws.",
    },
];

function Careers() {
    const [active, setActive] = useState("Health & Civil");
    const [activeContent, setActiveContent] = useState("About Leidos");
    const selected = filters.find((f) => f.name === active);
    const selectedContent = contents.find((c) => c.name === activeContent);


    return (
        <>
            <section className="md:px-0 px-5 relative w-full bg-gradient-to-r from[#335f80] to-[#335f80] overflow-hidden">
                {/* Overlay with clip path for md and above */}
                <div className="min-h-[300px] py-10 h-auto flex items-center relative md:inset-0 md:[clip-path:polygon(90%_0%,100%_60%,60%_100%,0%_100%,0_0)] md:bg-gray-600 md:pe-20 md:w-2/3 z-10 wow animate__animated animate__fadeInLeft wow">
                    <div className="md:pe-20 flex flex-col items-start max-w-xl mx-auto md:mx-0 md:ml-16 md:my-auto justify-center">
                        <h2 className="font-extrabold wow animate__animated animate__fadeInRight text-5xl md:text-6xl text-white leading-snug">
                            FIND YOUR NEW CAREER PATH AT LEIDOS
                        </h2>
                        <div className="max-w-[400px] mt-7 w-full relative bg-white inline-block">
                            <input type="text" name="search" id="search" placeholder='Enter Keywords, Job ID, or Title' className='p-3 bg-transparent border-none w-full' />
                            <BsSearch size={22} className='absolute top-1/2 right-5 -translate-y-1/2 text-[#6c87a5]' />
                        </div>
                    </div>
                </div>
            </section>

            <section className="py-12 px-4 md:px-8">
                <div className="max-w-6xl mx-auto">
                    <h2 className="text-2xl md:text-3xl capitalize mb-8">Featured Careers</h2>
                    <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
                        {insights.slice(0, 4).map((insight, index) => (
                            <div
                                key={index}
                                className={`wow animate__animated animate__fadeInUp bg-white shadow-md hover:shadow-lg transition-shadow duration-300 flex flex-col`}
                                data-wow-delay={index * 0.4 + "s"}
                            >
                                <div className="relative w-full h-48">
                                    <Image
                                        src={insight.image}
                                        alt={insight.title}
                                        fill
                                        className="object-cover"
                                    />
                                </div>
                                <div className="p-5 flex items-start flex-col flex-grow">
                                    <h3 className="text-xl font-semibold mb-2 text-[#6c87a5]">
                                        {insight.title}
                                    </h3>
                                    <p className="text-gray-700 text-base flex-grow">
                                        {insight.description}
                                    </p>
                                    <Link
                                        href={insight.buttonLink}
                                        className="mt-4 !inline-block px-5 py-2 rounded-md text-base font-semibold text-white transition hover:bg-[#335f80] bg-[#6c87a5]"
                                    >
                                        {insight.buttonText}
                                    </Link>
                                </div>
                            </div>
                        ))}
                    </div>
                    <div className="wow animate__animated animate__fadeInUp flex items-center justify-center" data-wow-delay="1.3s">
                        <Link href={"/insights"} className="inline-flex !mx-auto cursor-pointer capitalize bg-[#6c87a5] p-3 mt-8 text-sm md:text-base font-bold text-white rounded-lg px-5 border-none hover:bg-[#335f80] hover:text-white items-center justify-center space-x-3">
                            <span className='text-nowrap'>View More Insights</span> <FiArrowRight size={18} />
                        </Link>
                    </div>
                </div>
            </section>


            <TextOverColor
                heading="Opportunities Around the World"
                paragraph="Everything we do is built on our commitment to doing the right thing for our customers, employees, and the communities we support worldwide. Learn more about the values and culture that are the foundation of our global business."
            />


            {/* Filterable Gallary */}
            <div className={`min-h-screen md:max-h-[500px] transition-all duration-700 bg-gradient-to-b ${selected.gradient} text-white flex items-center`}>
                <div className="max-w-6xl mx-auto px-4">
                    {/* Filters */}
                    <div className="flex flex-wrap gap-3 justify-start md:justify-center mb-16 md:mb-32">
                        {filters.map((filter) => (
                            <button
                                key={filter.name}
                                onClick={() => setActive(filter.name)}
                                className={`text-base md:text-lg font-medium transition duration-300 relative group`}
                            >
                                <span
                                    className={`${active === filter.name ? "underline" : "no-underline"
                                        }`}
                                >
                                    {filter.name}
                                </span>
                            </button>
                        ))}
                    </div>

                    {/* Content */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-center animate-fadeIn">
                        <div className="space-y-6">
                            <h2 className="text-4xl font-bold animate-slideInLeft">
                                {selected.heading}
                            </h2>
                            <p className="text-lg leading-relaxed animate-slideInLeft delay-100">
                                {selected.paragraph}
                            </p>
                            <button className="bg-white text-black px-6 py-3 rounded-full inline-flex items-center gap-2 font-semibold animate-fadeInUp hover:scale-105 transition-transform">
                                Learn More <FiArrowRight size={20} />
                            </button>
                        </div>
                        <div className="flex justify-center md:justify-end animate-slideInRight">
                            <Image
                                src="/images/section-bg.jpg"
                                alt="section-img"
                                width={600}
                                height={600}
                                className="object-cover rounded-xl shadow-lg"
                            />
                        </div>
                    </div>
                </div>
            </div>

            <section className="py-16 bg-gradient-to-r from-green-100 to-[#cbced0] px-3">
                <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white hover:bg-[#6c87a5] p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto group-hover:text-white">
                            Utilities
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900 group-hover:text-white">
                            Utilities are under pressure to respond to changing regulations, energy demand, severe weather, improve operational efficiency, and integrate renewable energy into the mix of power generation. We help utilities evolve in the dynamic power marketplace.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5] group-hover:text-white">
                            <span>View Our Services</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white hover:bg-[#6c87a5] p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0.3s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto group-hover:text-white">
                            Investors & Developers
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900 group-hover:text-white">
                            Leidos serves the full range of sponsors, lenders, investors, and owners doing business in the energy industry, from private equity with diverse portfolios to institutional investors charged with preserving and growing capital and many more.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5] group-hover:text-white">
                            <span>More On Investors & Developers</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white hover:bg-[#6c87a5] p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0.6s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto group-hover:text-white">
                            Commercial & Industrial
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900 group-hover:text-white">
                            From industrial manufacturers to commercial businesses to public entities, we help customers build programs that deliver energy and costs savings. Our experts design, implement, and manage an effective energy program that's right for your organization.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5] group-hover:text-white">
                            <span>View Our Services</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                </div>
            </section>


            <section className="py-16 bg-gradient-to-r bg-white px-3">
                <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white cursor-pointer p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto">
                            Lorem, ipsum dolor?
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat nemo recusandae ex quaerat animi. Totam laborum in hic cupiditate itaque soluta nihil officia sapiente error vero ipsam velit perferendis, molestiae fuga porro debitis nobis. Architecto quidem ex placeat ipsa ipsum.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5]">
                            <span>Application Information</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white cursor-pointer  p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0.3s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto ">
                            Investors & Developers
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900 ">
                            Leidos serves the full range of sponsors, lenders, investors, and owners doing business in the energy industry, from private equity with diverse portfolios to institutional investors charged with preserving and growing capital and many more.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5] ">
                            <span>Application Information</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                    {/* Card */}
                    <div className="rounded-lg group py-10 bg-white cursor-pointer  p-5 md:p-10 wow animate__animated animate__fadeInUp" data-wow-delay="0.6s">
                        <h4 className="text-2xl md:text-3xl font-bold text-[#6c87a5] text-center mx-auto ">
                            Commercial & Industrial
                        </h4>
                        <p className="text-center text-base md:text-lg my-4 text-gray-900 ">
                            From industrial manufacturers to commercial businesses to public entities, we help customers build programs that deliver energy and costs savings. Our experts design, implement, and manage an effective energy program that's right for your organization.
                        </p>
                        <Link href="/" className="flex items-center justify-center space-x-2 text-[#6c87a5] ">
                            <span>Application Information</span> <BsArrowRight size={14} />
                        </Link>
                    </div>

                </div>
            </section>



            <section className="max-w-4xl mx-auto bg-white">
                <div className="flex gap-4 flex-col md:flex-row flex-wrap md:flex-nowrap">
                    <p className='w-full md:w-2/3 text-base md:text-lg'>Hello and thank you for visiting Leidos careers! My name is Chris Scalia and I manage recruiting efforts for Leidos. Our Talent Acquisition team is dedicated to ensuring your job search at Leidos is both a productive and a positive experience. Building your search profile can be helpful so that you are notified when openings come available. Our platform provides the ability for you to see your status through the hiring process by logging in with your existing profile. Lastly, many of our opportunities are chat enabled where you can immediately request to connect with a live recruiter. Thanks again for your interest in Leidos and feel free to let me know how we are doing at <a href="/" className='text-[#6c87a5] underline'>chris.a.scalia@leidos.com.</a>
                    </p>
                    <div className="w-full md:w-1/3">
                        <div className="relative w-full h-[300px]">
                            <Image
                                src="/images/AI DRIVE.jpg"
                                alt="Get it on iBooks"
                                fill
                                className="object-cover"
                            />
                        </div>
                    </div>
                </div>
            </section>

            <section className="px-3 py-16 mx-auto max-w-xl">
                <h2 className="animate__animated animate__fadeInLeft wow text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start" data-wow-delay="0s">
                    Fraud and Scam Awareness
                </h2>
                <p className="mb-7 animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.2s">
                    Beware of fake employment opportunities using Leidos&apos; name. Leidos will never ask you to provide payment-related information during any part of the employment application process (i.e., ask you for money), nor will Leidos ever advance money as part of the hiring process (i.e., send you a check or money order before doing any work). Further, Leidos will only communicate with you through emails that are generated by the Leidos.com automated system never from free commercial services (e.g., Gmail, Yahoo, Hotmail) or via WhatsApp, Telegram, etc. If you received an email purporting to be from Leidos that asks for payment-related information or any other personal information (e.g., about you or your previous employer), and you are concerned about its legitimacy, please make us aware immediately by emailing us at <span className='text-[#6c87a5] underline'>Leidos Careers Fraud.</span>
                </p>
                <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.4s">
                    If you believe you are the victim of a scam, contact your local law enforcement and <span className='text-[#6c87a5] underline'>report the incident to the U.S. Federal Trade Commission.</span>
                </p>
                <hr className='my-10' />
                <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.6s">
                    All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability, veteran status or any other characteristic protected by law.
                </p>
                <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.8s">
                    An equal opportunity employer/disability/vet.
                </p>
                <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="1s">
                    Employment legal notices can be viewed on the U.S. Department of Labor's website and in Leidos' EEO Statement for Applicants.
                </p>
                <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="1.2s">
                    A link to Labor Condition Applications is provided to show any H-1B workers who are being sought by Leidos. These include the occupational classification, the wages offered, the period of employment, the locations at which the H-1B worker will be employed. The LCA and accompanying documents are available for <span className='text-[#6c87a5]'>public viewing.</span>
                </p>
            </section>








            {/* Filterable Content */}
            <div className={`transition-all duration-700 text-black flex flex-col  items-stretch`}>
                {/* Filters */}
                <div className="shadow-sm flex flex-wrap gap-3 justify-start md:justify-center pb-12 mb-5">
                    {contents.map((content) => (
                        <button
                            key={content.name}
                            onClick={() => setActiveContent(content.name)}
                            className={`text-base md:text-lg rounded-lg font-medium transition duration-300 relative group`}
                        >
                            <span
                                className={`${activeContent === content.name ? "bg-[#6c87a5] p-2 text-white" : "p-2 text-black"
                                    }`}
                            >
                                {content.name}
                            </span>
                        </button>
                    ))}
                </div>
                <div className="">
                    {/* Content */}
                    <div className="max-w-6xl mx-auto mt-5 px-4">
                        <p className="text-base md:text-lg text-center leading-relaxed animate-slideInUp">
                            {selectedContent.paragraph}
                        </p>
                    </div>
                </div>
            </div >

            <ContactForm />
        </>
    )
}

export default Careers;
