import ContactForm from '@/components/ContactForm';
import TextOverColor from '@/components/TextOverColor';
import Link from 'next/link';
import React from 'react'
import { BsArrowRight } from 'react-icons/bs';
function Contact() {
  return (
    <>
      <section className="md:px-0 px-5 relative w-full bg-gradient-to-r from[#335f80] to-[#335f80] overflow-hidden">
        {/* Overlay with clip path for md and above */}
        <div className="min-h-[300px] py-10 h-auto flex items-center relative md:inset-0 md:[clip-path:polygon(90%_0%,100%_60%,60%_100%,0%_100%,0_0)] md:bg-gray-600 md:pe-20 md:w-1/2 z-10 wow animate__animated animate__fadeInLeft wow">
          <div className="md:pe-20 flex flex-col items-start max-w-xl mx-auto md:mx-0 md:ml-16 md:my-auto justify-center">
            <h2 className="font-extrabold wow animate__animated animate__fadeInRight text-5xl md:text-6xl text-white leading-snug">
              Contact
            </h2>
            <p className="text-base md:text-lg text-white my-3">
              Contact us with your questions and feedback using the contact form below.
            </p>
          </div>
        </div>
      </section>


      <section className="px-3 animate__animated animate__fadeInLeft wow pb-5 pt-14 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Fraud and Scam Awareness
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          Beware of fake employment opportunities using Leidos&apos; name. Leidos will never ask you to provide payment-related information during any part of the employment application process (i.e., ask you for money or to purchase cryptocurrency), nor will Leidos ever advance money as part of the hiring process (i.e., send you a check or money order before doing any work). Further, Leidos will only communicate with you through emails that are generated by the Leidos.com automated system never from free commercial services (e.g., Gmail, Yahoo, Hotmail) or via WhatsApp, Telegram, etc. If you received an email purporting to be from Leidos that asks for payment-related information or any other personal information (e.g., about you or your previous employer), and you are concerned about its legitimacy, please make us aware immediately by emailing us at LeidosCareersFraud@leidos.com. Additionally, you can verify the legitimacy of any employment opportunity by finding the job posting on our <span className="text-[#6c87a5]">career site</span> or by reaching out through the contact us form above and selecting <strong>Career Question</strong> as your inquiry type.
        </p>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.6s">If you believe you are the victim of a scam, contact your local law enforcement and <span className="text-[#6c87a5]">report the incident to the U.S. Federal Trade Commission.</span></p>
      </section>

      <section className="px-3 animate__animated animate__fadeInLeft wow py-5 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Having technical issues applying for a job?
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          If you are having technical issues applying for a position on our career site, choose <span className="text-[#6c87a5]">Career Question</span> in the Type of Request drop-down list below to request help.
        </p>
      </section>

      <section className="px-3 animate__animated animate__fadeInLeft wow py-5 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Are you an employee and need IT help?
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          The Leidos Service Desk is a centralized support center for computing resources and information needs for employees. View the information below to <span className="text-[#6c87a5]">learn how to get help online or call the help desk.</span>
        </p>
      </section>


      <section className="px-3 animate__animated animate__fadeInLeft wow py-5 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Need assistance due to a disability or limited English proficiency?
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          If you have a disability and need help using our site, use the drop-down list above and choose <span className="text-[#6c87a5]">Accommodation Request</span> to request help.
        </p>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          Leidos ensures nondiscrimination in all programs and activities in accordance with the Title VI of the Civil Rights Act of 1964. If you need more information or special assistance for persons with disabilities or limited English proficiency, contact the<span className="text-[#6c87a5]"> Leidos Employee Services.</span>
        </p>
      </section>


      <section className="px-3 animate__animated animate__fadeInLeft wow py-5 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Do you have a question about Leidos QTC Health Services?
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          If you need assistance or wish to request information specific to Leidos QTC Health Services, please reach out to a member of the team by phone at 800-260-1515 or 909-859-2100. Alternatively, you can submit your inquiry online through our contact form. We&apos;re here to help!
        </p>
        <Link href={"/"} className="animate__animated animate__fadeInLeft wow rounded-3xl mt-5 bg-[#6c87a5] p-3 px-6 hover:bg-[#335f80] inline-flex items-center justify-center space-x-3 text-white" data-wow-delay="0.6s"><span>Contact</span> <BsArrowRight size={18} /></Link>
      </section>

      <section className="px-3 animate__animated animate__fadeInLeft wow py-5 mx-auto max-w-2xl" data-wow-delay="0s">
        <h2 className="text-[#6c87a5] font-bold leading-tight text-4xl md:text-5xl text-start">
          Do you need proof of employment and/or income?
        </h2>
        <p className="animate__animated animate__fadeInLeft wow text-start my-4 text-base md:text-lg" data-wow-delay="0.3s">
          Current and former Leidos (formerly known as SAIC, employment prior to September 28, 2013) employees can provide proof of employment and income with secure, 24/7 access through a toll-free number and website.
        </p>
        <Link href={"/"} className="animate__animated animate__fadeInLeft wow rounded-3xl mt-5 bg-[#6c87a5] p-3 px-6 hover:bg-[#335f80] inline-flex items-center justify-center space-x-3 text-white" data-wow-delay="0.6s"><span>Employment Verification</span> <BsArrowRight size={18} /></Link>
      </section>




        <TextOverColor
                heading="Ethics Helpline"
                paragraph="Leidos has a strong culture of ethics and integrity. Our Code of Conduct is a broad statement of principles for conducting business according to the highest ethical standards. We take every report seriously and have zero tolerance for retaliation of any kind against individuals who, in good faith, raise questions or report concerns. You may submit an online report or call using the Ethics Helpline, which is hosted by an independent, third-party provider."
                btns={[{href : "/" , text : "FILE A REPORT"}]}
            />
      
      <ContactForm />
    </>
  )
}
export default Contact;
